import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";
// import { GoogleOAuthProvider } from "@react-oauth/google";
import Providers from "./providers";
const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata = {
  title: "OxyGen Script",
  description: "Generated by Mahbub Ahmed Turza",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}> */}
      <body className={`${quicksand.variable} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <ToastContainer />
        </Providers>
      </body>
      {/* </GoogleOAuthProvider> */}
    </html>
  );
}
