import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata = {
  title: "OxyGen Script",
  description: "Generated by Mahbub Ahmed Turza",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
